version: '3.7'
services:
  moodle:
    image: moodlehq/moodle-php-apache:7.2
    volumes:
      - ${MOODLE_DIR}:/var/www/html
      - ./:/var/www/html/local/smf
    ports:
      - "${MOODLE_PORT}:80"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"